### ISSUE TITLE
求一个padavan版的n2n-V2

### ISSUE THREAD

**Issue by simonchan6688** [lucktu/n2n#1]
求一个padavan版的n2n-V2, 请附上食用说明。谢谢

**Comment by lucktu** [comment]
直接上这里根据自己的CPU下载即可，例如MTK7620、7621可以使用 n2n_v2_linux_mipsel ...
https://github.com/lucktu/n2n/tree/master/Linux

使用方法就是，将下载回来的压缩包解压，将里面的edge上传到padavan的/etc/storage目录，修改其属性为0755，然后就可以使用命令行的方式（可以加入路由器启动后的代码里）运行edge了。为了路由器重启不丢失，需要在管理页面运行保存到闪存。
