### ISSUE TITLE
N2N可以添加以服务方式自启？

### ISSUE THREAD

**Issue by jelly0925** [lucktu/n2n#11]
佬大N2N可以添加以服务方式自启，现在每次N2N开机都需要登录系统才能启动，谢谢哦

**Comment by lucktu** [comment]
这个不是本站的事，我也只是收集QQ群里的大神们的作品而已。

虽然不便以服务方式启动，但是也可以加入其他方式的开机启动吧，例如ubuntu，加入rc.local，windows加入启动选项里去，都是可以的，大家都在这么用。
