### ISSUE TITLE
macbook m1能编译吗

### ISSUE THREAD

**Issue by privking** [lucktu/n2n#12]
请问macbook m1能编译吗

**Comment by lucktu** [comment]
我们没有这样的环境，不方便编译。其实自己编译也很方便的呀，不知你遇到什么问题了？
第一步，安装一些依赖：git make gcc automake libssl-dev cmake
第二步，下载源码： git clone https://github.com/ntop/n2n.git
第三步，编译
cd n2n
./autogen.sh
./configure
make
或者
cd n2n
cmake ./
make

你试试，编译出来了共享一下
参考： http://www.lucktu.com/archives/755.html
