### ISSUE TITLE
hin2n_211018.ipa(已用自己的apple id签名过) 无法在IOS 15.2.1中正常工作

### ISSUE THREAD

**Issue by StarlitSkyline** [lucktu/n2n#14]
![图片2](https://user-images.githubusercontent.com/40024272/153749307-adf52d3d-bc11-4bd9-845a-c648143565a2.jpg)
系统：iOS 15.2.1
手机：iphone 13

1. 保存过后，再次编辑，会发现除了密码，其他字段全部不可见了，但是值还在。
2. 左上角的时间和右上角的手机信号、wifi等图标没了。
3. 同样的设置Android客户端能连上，但是ios却一直连不上，没有出现vpn连接。以下是连接的日志：
![3](https://user-images.githubusercontent.com/40024272/153750038-84fc69cd-4b6d-4a19-8c2f-b74d74e2d712.jpg)

4.终止连接以后，无法再次点击上面的按钮重新连接，必须kill掉，重新进入app才可以。

**Comment by Oliver0624** [comment]
这个程序是我和一个同事一起写的。你手上的版本可能旧了一点，你可以到[这个地址](https://github.com/oliver0624/hin2n-ios)去clone最新代码自行编译使用。

**Comment by lucktu** [comment]
谢谢反馈！原作者说他们测试没有这样的问题。
请用这里最新的源码编译试试呢？
https://github.com/Oliver0624/hin2n-ios

https://github.com/Oliver0624/hin2n-ios/issues/1

**Comment by StarlitSkyline** [comment]
:( 目前手上没有mac，无法自己编译 T^T

**Comment by lucktu** [comment]
哎，可惜我也不会，。。。
