### ISSUE TITLE
edge not updated

### ISSUE THREAD

**Issue by Klutton** [lucktu/n2n#18]
My friend is trying to connect to my supernode, but on the server, it keeps showing assign IP 10.157.41.41/24 to tap adapter of edge but does not show "updated edge", [2022-11-17 13:23:07] [OK] edge <<< ================ >>> supernode  is shown on client, I wonder why this is happening and how I can fix this

**Comment by lucktu** [comment]
supernode和edge尽量用相同版本，参数尽量一致，如果还不能连接，可以部分使用固定IP。

**Comment by Klutton** [comment]
> supernode和edge尽量用相同版本，参数尽量一致，如果还不能连接，可以部分使用固定IP。

问题在于，使用相同客户端情况下，我一部分朋友正常使用，只有一个出现了这样的情况

**Comment by lucktu** [comment]
会不会是因为他那里封了UDP？

**Comment by Klutton** [comment]
他那里能连上我的zerotier但是这个会出现这种情况

**Comment by Klutton** [comment]
> 会不会是因为他那里封了UDP？

方便加个qq仔细聊吗？我不知道github能不能私发qq号，这样安全点，或者你不介意的话可以发下你的吗
