### ISSUE TITLE
群晖搭建 n2n  supernode edge之间相互ping不通

### ISSUE THREAD

**Issue by juvham** [lucktu/n2n#2]
群晖搭建 n2n  supernode edge之间相互ping不通

是还需要做什么额外的配置么？有没有相关的教程

**Comment by lucktu** [comment]
群晖较新的系统（6.2以后），运行edge的开始，有正常的路由表，但是一会儿它就会删除这一条路由表，让edge工作不正常，需要手动加入。更详细的见我的博客文章：
http://www.lucktu.com/archives/754.html
