### ISSUE TITLE
v3的FreeBSD版本

### ISSUE THREAD

**Issue by Alex6357** [lucktu/n2n#23]
已经编译好v3.0的FreeBSD版本，但是有一些严重的问题
第一，无法保持在前台运行，并且输出有些排版问题
第二，kill掉edge进程之后，会造成FreeBSD无法上网，需要重启网络
[https://github.com/Alex6357/n2n-for-FreeBSD](https://github.com/Alex6357/n2n-for-FreeBSD)

**Comment by lucktu** [comment]
你根据自己的CPU试试这里的 linux 下的程序呢？
