### ISSUE TITLE
如何使用这里的文件 https://github.com/lucktu/n2n/tree/master/Windows

### ISSUE THREAD

**Issue by tlsalex** [lucktu/n2n#3]
我在寻找windows下的n2n v2.6版，
跌跌撞撞找了https://github.com/lucktu/n2n/tree/master/Windows，
但不知道怎么用这里的文件，
我是要利用这些文件重新编译吗？

**Comment by lucktu** [comment]
不是意思发现晚了：这是已经编译好的，下载后直接用代码行运行。

如果你要自己编译，请去官方下载源码进行
https://github.com/ntop/n2n
