### ISSUE TITLE
大神，请问如何运行n2n_v2s_mac_x64_v2.1.0_r124_by_bluce.zip里面的edge文件？

### ISSUE THREAD

**Issue by David3434** [lucktu/n2n#5]
n2n_v2s版节点服务器已正常可以用
现想要在mac catalina 运行n2n_v2s客户端,请问如何操作？

感谢！

**Comment by lucktu** [comment]
只能像windows下一样, dos下运行 edge... 的代码行吧. 我不熟悉mac.

**Comment by David3434** [comment]
好的，感谢回复！
我这就试试看
