### ISSUE TITLE
路由器上安装n2n，能ping通，但是无法通过网页访问

### ISSUE THREAD

**Issue by ACvsRM** [lucktu/n2n#8]
单位电脑安装easyn2n（n2n-v2版本），家里联通内网，路由器刷的koolshare梅林，家里电脑安装的easyn2n（n2n-v2版本）。
1、单位电脑可以访问家里电脑
2、路由器安装n2n_v2_linux_arm_v2.7.0_r525_all_by_heiye.zip成功，能够开机启动n2n，路由器可以ping通单位电脑和家里电脑的虚拟局域网ip
3、无论家里还是单位电脑均无法通过虚拟局域网ip访问路由器网页。

奇怪的是我查看路由器开放端口，通过4个IP（路由器对内部局域网的IP、路由器获取的联通内部IP、真实的联通公网IP、虚拟局域网的IP）发现端口均不一致，路由器开放的18181端口，仅在路由器获取的联通内部IP显示开放，在虚拟局域网并没有开放。
不知道是何原因。

**Comment by lucktu** [comment]
抱歉，发现太晚了。
建议将n2n运行参数中的MTU修改为1290，或者1386，建议设置小一点，通讯的两边都设置一下吧。
